options = {
    'frm_thinborder_clr':      0x585a5d,
    'frm_full_bg_a':           0xff7f00,
    'frm_full_title_a':        0xffffff,
    'frm_full_bg_i':           0xe0dfde,
    'frm_full_title_i':        0x000000,
    'frm_full_bottom_brdr_a':  0xff7f00,
    'frm_full_bottom_brdr_i':  0xe0dfde,
    'frm_full_bottom_brdr_sz': 5,
    'frm_full_button_bg_a':    0xff7f00,
    'frm_full_button_bg_i':    0xffffff,
    'frm_full_button_fg_a':    0xffffff,
    'frm_full_button_fg_i':    0x000000,
    'frm_border_bg_a':         0xbb0000,
    'frm_border_bg_i':         0x008800,
    'frm_border_bg_c':         0x3366ff,
    'frm_border_thin_clr':     0x000000,
    'frm_border_brdr_sz':      3,
    'cycle_brdr_sz':           5,
    'cycle_brdr_clr':          0x585a5d,
    'cycle_bg':                0xcbcbcb,
    'cycle_icn_sz':            64,
}

